### ISSUE TITLE
Module ./tools/jest/jest.setup.js in the setupFiles option was not found.​​

### ISSUE THREAD

**Issue by jcyh0120** [axelnormand/react-native-typescript-wallaby-jest#1]
I got this error after following the steps in readme.

`Validation Error:​​
​​​​
​​  Module ./tools/jest/jest.setup.js in the setupFiles option was not found.​​
​​​​
​​  Configuration Documentation:​​
​​  https://facebook.github.io/jest/docs/configuration.html​​`

**Comment by jcyh0120** [comment]
I solved this by adding the 'setup-jest.js' to wallaby.js. I don't know how to make a pull request yet. So I will just paste it here.

```
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.ts?(x)',
      'src/**/*.js?(x)',
      'src/**/*.json',
      '!src/**/*.test.ts?(x)',
      'package.json',
      'tsconfig.json',
      'jest.config.js',
      'tools/jest/**/*.js', <--- add this line
    ],
```

And here's the reference about this issue:
https://github.com/wallabyjs/public/issues/1537

Thanks for this awesome skeleton. There are too many settings. I just cannot figure out how to do this from a plain ts-react-native project.

**Comment by axelnormand** [comment]
wow awesome thanks for the issue and fix. Glad you found it useful!

let me merge your change in now.
In fact i think its easier for me to add: `'tools/**/*.js',`
